---
- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ user_username }}"
    comment: "Created by ansible"
    create_home: "{{ user_create_home | bool }}"
    home: "/home/{{ user_username }}"
    shell: /bin/bash
    generate_ssh_key: "{{ user_create_home | bool and user_generate_ssh_key | bool }}"

- name: Modify home directory permissions
  when: user_create_home
  become: true
  ansible.builtin.file:
    path: "/home/{{ user_username }}/"
    state: directory
    mode: "750"

- name: Fetch generated public key
  when: user_create_home | bool and user_generate_ssh_key | bool
  become: true
  ansible.builtin.fetch:
    src: "/home/{{ user_username }}/.ssh/id_rsa.pub"
    dest: "./keys/{{ inventory_hostname }}/{{ user_username }}.pub"
    flat: true
