---
- name: Add user
  when: user_uninstall == false
  block:
    - name: Setup
      when: user_username | length > 0
      ansible.builtin.include_tasks: setup.yml

- name: Remove user
  when: user_uninstall == true
  block:
    - name: Clean
      when: user_username | length > 0
      ansible.builtin.include_tasks: clean.yml
